version: '3.9'
services:
  frontend:
    build: ./app/front
    ports:
      - 3000:3000
    working_dir: /app-frontend
    volumes:
      - ./app/front/src:/app-frontend/src
    depends_on:
      - backend
  backend:
    container_name: app_backend
    build: ./app/back
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    volumes:
      - ./app/back/src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
